---
title: "Hypothesis_Testing"
output:
  pdf_document: default
  html_document: default
date: "2025-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
df <- read.csv("../data/indian_companies_processed.csv", stringsAsFactors = FALSE)
```

```{r}
# Test: Is the average RATING different from 3.5?
# H0: mean = 3.5
# H1: mean ≠ 3.5
cat("\n--- ONE-SAMPLE T-TEST (RATING vs 3.5) ---\n")
one_sample_test <- t.test(df$RATING, mu = 3.5)
print(one_sample_test)
```

```{r}
# Test: Do Bangalore companies have different PACKAGE values?
# H0: μ_Bangalore = μ_NonBangalore
# H1: μ_Bangalore ≠ μ_NonBangalore
df$PACKAGE <- as.numeric(df$PACKAGE)

blr <- subset(df, INDIA.HQ == "Bangalore / Bengaluru")$PACKAGE
non_blr <- subset(df, INDIA.HQ != "Bangalore / Bengaluru")$PACKAGE

blr <- blr[!is.na(blr)]
non_blr <- non_blr[!is.na(non_blr)]

t.test(blr, non_blr, var.equal = FALSE) #Welch's test
```

```{r}
# Test: Does average PACKAGE differ by INDUSTRY?
# H0: All industries have same mean PACKAGE
# H1: At least one differs
cat("\n--- ANOVA TEST (PACKAGE by INDUSTRY) ---\n")
anova_model <- aov(PACKAGE ~ INDUSTRY, data = df)
summary(anova_model)
```

```{r}
# Test: Are INDUSTRY and INDIA.HQ dependent?
# H0: They are independent
# H1: They are dependent
cat("\n--- CHI-SQUARE TEST (INDUSTRY vs INDIA.HQ) ---\n")
tab <- table(df$INDUSTRY, df$INDIA.HQ)

chi_test <- chisq.test(tab)
print(chi_test)
```

```{r}

# Test: if Packages are related to Years old or not. (Numeric)
# H0: ρ = 0 (no correlation)
# H1: ρ ≠ 0
cat("\n--- PEARSON CORRELATION (YEARS.OLD vs PACKAGE) ---\n")
df$YEARS.OLD <- as.numeric(df$YEARS.OLD)
df$PACKAGE <- as.numeric(df$PACKAGE)

corr_df <- df[, c("YEARS.OLD", "PACKAGE")]
corr_df <- corr_df[complete.cases(corr_df), ]

cor.test(corr_df$YEARS.OLD, corr_df$PACKAGE, method = "pearson")

```


Across the hypothesis tests, several clear patterns emerge:  
  - Average ratings are significantly higher than 3.5.  
  - Bangalore companies offer higher packages than other cities.  
  - Industry strongly influences package.  
  - Industry and headquarters location are strongly associated.  
  - Company age has only a negligible relationship with package offered.  
